name: macrosystems
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  
  # Core scientific python
  - numpy
  - matplotlib
  - rioxarray
  - geopandas
  - gdal
  - osmnx
  
  - rasterio
  - geemap
  - earthengine-api
  - google-auth
  - google-api-python-client
  - PyDrive2
  - xarray
  - zarr
  - dask
  - folium
  - leafmap
  - pyproj

  # Jupyter Lab Environment & Kernel
  - papermill
  - autopep8
  - jupyterlab
  - notebook
  - ipython
  - nbclean
  - nbresuse
  - jupyterlab-geojson
  - nb_conda_kernels
  - ipykernel
  - gh
  - ipyleaflet
  - jupyterlab_widgets
  - ipywidgets
  - nodejs

  # For GEDI downloading
  - contextily
  - netcdf4
  - pydap
  - seaborn
 